### ISSUE TITLE
为什么训练20多轮后不动了

### ISSUE THREAD

**Issue by 200N** [chandlerbing65nm/FakeImageDetection#1]
<img width="845" alt="image" src="https://github.com/chandlerbing65nm/FakeImageDetection/assets/86503820/faa4681f-f4f0-414f-b5a9-2c77925fd264">

**Comment by chandlerbing65nm** [comment]
Just stop the training then resume from the last checkpoint. I have mentioned it in the readme [here](https://github.com/chandlerbing65nm/FakeImageDetection/blob/e2c29d45addf559eba3e5b2bb6de22e5dc039548/README.md?plain=1#L252C1-L253C1).

**Comment by chandlerbing65nm** [comment]
It's a bug that I did not solve. Most likely from the distributed training code.

**Comment by 200N** [comment]
你好，请问bug现在解决了吗
我在训练时会出现这种情况
